### ISSUE TITLE
How to deal with discrete feature?

### ISSUE THREAD

**Issue by YYangZiXin** [jbr-ai-labs/bbo-challenge-jetbrains-research#1]

**Comment by bruce-willis** [comment]
Hey @YYangZiXin! Just use `'type': 'int'` in configuration space.

I suggest looking at @zacheberhart-kd fork: https://github.com/zacheberhart-kd/bbo-challenge-jetbrains-research.
For instance, in the readme file: https://github.com/zacheberhart-kd/bbo-challenge-jetbrains-research#setting-the-search-space parameters `x` and `y` are discrete.

For complete example see this file: https://github.com/zacheberhart-kd/bbo-challenge-jetbrains-research/blob/6233ae3bcdb4cddce9a29e74123313a4228ae6e9/run.py
